# Generated by Django 4.2.2 on 2023-08-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('camp_id', models.CharField(max_length=3)),
                ('contact', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=7)),
            ],
        ),
    ]
