# Generated by Django 4.2.2 on 2023-08-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_id', models.CharField(max_length=3)),
                ('camp_name', models.CharField(max_length=20)),
                ('camp_add', models.CharField(max_length=60)),
                ('camp_district', models.CharField(max_length=20)),
                ('camp_state', models.CharField(max_length=20)),
                ('camp_man', models.CharField(max_length=20)),
                ('man_id', models.CharField(max_length=5)),
                ('camp_img', models.ImageField(upload_to='Camp_Images')),
                ('man_contact', models.IntegerField(max_length=10)),
            ],
        ),
    ]
