# Generated by Django 4.2.2 on 2023-08-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_camp_curr_capacity_camp_total_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='rat_soap',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camp',
            name='rat_towel',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
